Update drain3_parser.py
Again the workaround for drain3::add_log_message().
this time, passing the list instead of the str.
(The error was:
 File "/usr/local/lib/python3.6/dist-packages/drain3-0.7.2-py3.6.egg/drain3/template_miner.py", line 84, in add_log_message
  File "/usr/local/lib/python3.6/dist-packages/drain3-0.7.2-py3.6.egg/drain3/drain.py", line 230, in add_log_message
AttributeError: 'NoneType' object has no attribute 'split'
)